import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).parent.parent))
from src.report import build_ranked_table, build_report_markdown, write_report
from src.cohorts import cohorts

_TEST_THEMES = {"benchmark": "ACWI", "themes": {
    "Semiconductors": {"ticker": "SOXX"},
    "Space": {"ticker": "UFO"},
    "Biotech": {"ticker": "XBI"},
}}


def test_markdown_has_all_sections():
    md = build_report_markdown("2026-06-25", "RANKED_TBL", "MOVERS_SEC")
    assert "# Sector Momentum Report — 2026-06-25" in md
    assert "> Analytical tooling, not investment advice." in md
    assert "## Rankings\nRANKED_TBL" in md
    assert "## Movers\nMOVERS_SEC" in md
    assert "*Generated by Sector Momentum Scanner. Last scan: 2026-06-25.*" in md


def test_write_report_uses_same_markdown(tmp_path):
    path = write_report("2026-06-25", "R", "M", output_dir=str(tmp_path))
    assert Path(path).read_text() == build_report_markdown("2026-06-25", "R", "M")


def test_ranked_table_renders_the_cohort_section():
    """build_ranked_table emits one section per cohort, ranked within it."""
    df = pd.DataFrame({
        "region": ["THEME"] * 3,
        "gics_sector": ["Semiconductors", "Space", "Biotech"],
        "composite": [1.0, 0.5, -0.1],
        "level_score": [0.5, 0.3, 0.0],
        "change_score": [0.5, 0.2, -0.1],
        "data_score": [1.0, 0.5, -0.1],
        "rank": [1.0, 2.0, 3.0],
        "delta_composite": [0.1, -0.1, -0.05],
        "delta_rank": [1.0, -1.0, -1.0],
        "emerging_flag": [True, False, False],
    })
    result = build_ranked_table(df, cohorts(_TEST_THEMES))

    assert "## Themes" in result
    assert "Semiconductors" in result
    assert "Space" in result
    assert "| 3 |" in result


def test_ranked_table_sections_follow_cohorts():
    """Section headers and their order come from the cohort list, not from a
    hardcoded region pair. This guarded the hardcoded-("US","EU") bug; it still
    guards it, since the retired sector rows remain in the scores table and a
    hardcoded loop would resurrect them."""
    df = pd.DataFrame([
        {"region": "THEME", "gics_sector": "Space", "composite": 0.9,
         "level_score": 0.5, "change_score": 0.4, "rank": 1,
         "delta_rank": 0, "delta_composite": 0.0, "emerging_flag": False},
        {"region": "US", "gics_sector": "Energy", "composite": 0.9,
         "level_score": 0.5, "change_score": 0.4, "rank": 1,
         "delta_rank": 0, "delta_composite": 0.0, "emerging_flag": False},
    ])
    md = build_ranked_table(df, cohorts({"themes": {"Space": {"ticker": "UFO"}}}))

    assert "## Themes" in md
    assert "## US Sectors" not in md
    assert "Energy" not in md, "a retired sector row reached the report"
