import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).parent.parent))
from src.report import build_ranked_table, build_report_markdown, write_report
from src.cohorts import cohorts

_TEST_UNIVERSE = {
    "us_sectors": {"Tech": "XLK", "Energy": "XLE"},
    "eu_sectors": {"Banks": "EXV1.DE", "Insurance": "EXH5.DE", "Chemicals": "EXV3.DE"},
}


def test_markdown_has_all_sections():
    md = build_report_markdown("2026-06-25", "RANKED_TBL", "MOVERS_SEC", "SWEDISH_SEC")
    assert "# Sector Momentum Report — 2026-06-25" in md
    assert "> Analytical tooling, not investment advice." in md
    assert "## Rankings\nRANKED_TBL" in md
    assert "## Movers\nMOVERS_SEC" in md
    assert "SWEDISH_SEC" in md
    assert "*Generated by Sector Momentum Scanner. Last scan: 2026-06-25.*" in md


def test_write_report_uses_same_markdown(tmp_path):
    path = write_report("2026-06-25", "R", "M", "S", output_dir=str(tmp_path))
    assert Path(path).read_text() == build_report_markdown("2026-06-25", "R", "M", "S")


def test_ranked_table_has_two_region_sections():
    """build_ranked_table should produce US and EU sections."""
    data = {
        "region": ["US", "US", "EU", "EU", "EU"],
        "gics_sector": ["Tech", "Energy", "Banks", "Insurance", "Chemicals"],
        "composite": [1.0, 0.5, 0.8, 0.3, -0.1],
        "level_score": [0.5, 0.3, 0.4, 0.2, 0.0],
        "change_score": [0.5, 0.2, 0.4, 0.1, -0.1],
        "data_score": [1.0, 0.5, 0.8, 0.3, -0.1],
        "rank": [1.0, 2.0, 1.0, 2.0, 3.0],
        "delta_composite": [0.1, -0.1, 0.2, 0.0, -0.05],
        "delta_rank": [1.0, -1.0, 0.0, 1.0, -1.0],
        "emerging_flag": [True, False, False, False, False],
    }
    df = pd.DataFrame(data)
    result = build_ranked_table(df, cohorts(_TEST_UNIVERSE))

    assert "## US Sectors" in result
    assert "## EU Sectors" in result
    us_section = result.split("## EU Sectors")[0]
    eu_section = result.split("## EU Sectors")[1]
    assert "Tech" in us_section
    assert "Energy" in us_section
    assert "Banks" in eu_section
    assert "| 3 |" in eu_section


def test_ranked_table_sections_follow_cohorts():
    """Section headers and their order come from the cohort list, not from a
    hardcoded ("US", "EU") pair."""
    import pandas as pd
    from src.report import build_ranked_table
    from src.cohorts import cohorts

    df = pd.DataFrame([
        {"region": "US", "gics_sector": "Energy", "composite": 0.9,
         "level_score": 0.5, "change_score": 0.4, "rank": 1,
         "delta_rank": 0, "delta_composite": 0.0, "emerging_flag": False},
    ])
    universe = {"us_sectors": {"Energy": "XLE"}}
    md = build_ranked_table(df, cohorts(universe))

    assert "## US Sectors" in md
    assert "## EU Sectors" not in md, "EU section emitted with no eu_sectors configured"


def test_swedish_overlay_matches_subsector_via_parent(tmp_path):
    import pandas as pd

    from src.report import build_swedish_overlay

    csv = tmp_path / "swedish_tickers.csv"
    csv.write_text(
        "ticker,name,gics_sector,market_cap_bn_sek,exchange\n"
        "SEB-A.ST,SEB A,Financials,300,Nasdaq Stockholm\n"
    )
    scores = pd.DataFrame([
        {"region": "EU", "gics_sector": "Banks", "composite": 2.0, "rank": 1},
    ])
    md = build_swedish_overlay(scores, swedish_tickers_path=str(csv), top_n=1)
    assert "Banks (EU)" in md        # displayed under the sub-sector's own name
    assert "SEB-A.ST" in md          # matched via parent Financials
