"""Plotly figure builders for dashboard charts."""

from __future__ import annotations

from datetime import date

import pandas as pd
import plotly.graph_objects as go
import plotly.io as pio

from dashboard.rows import _safe_float


# ---------------------------------------------------------------------------
# Shared constants
# ---------------------------------------------------------------------------

_WARM_PALETTE = [
    "#5A6F49",  # green-600
    "#A55A3C",  # terra-500
    "#738A5F",  # green-500
    "#BF6F50",  # terra-400
    "#455636",  # green-700
    "#83462E",  # terra-600
    "#6A8599",  # info blue-gray
    "#8F8568",  # beige-500
    "#2F3C25",  # green-800
    "#5E3121",  # terra-700
]

_SCORE_SIGNAL_COLORS: dict[str, str] = {
    "composite":    "#5A6F49",
    "level_score":  "#8FA77A",
    "change_score": "#A55A3C",
    "data_score":   "#6A8599",
    "rank":         "#8F8568",
}

# The signal columns _build_drilldown_data plots — a constant, not
# data-derived, so callers that only need the label list (e.g.
# build_sectors_context's `signals_list`) don't have to invoke the builder
# (and pay for building every sector's drilldown figure) just to read it.
_DRILLDOWN_SIGNALS: list[str] = [
    "composite", "level_score", "change_score", "data_score", "rank"
]


# ---------------------------------------------------------------------------
# Dark-theme colour map for the 7 baked Plotly figures
# ---------------------------------------------------------------------------
#
# Six entries reuse the already-approved dark token values from
# _foundation.css.j2 (the palette a browser mockup validated) — anything
# here that IS a semantic token in the light theme maps to that same
# token's dark value, so a chart line and a CSS-driven UI element that
# happen to share a colour still match after theming.
#
# The remaining entries have no semantic-token equivalent (chart-only
# categorical colours: the 10-line History palette, the RS-blue-gray
# "Data" signal colour, two audit-flagged off-system near-misses used only
# in the sentiment scatter). Those were generated by a damped HSL lightness
# inversion (L' = 1 - (1-L)*0.62, clamped to [0.42, 0.82], S *= 0.92) and
# every one measured >=4.0:1 against the dark chart background (#2A2619)
# before being written down here — see the 2026-08-10 planning session for
# the actual numbers. Two near-white greys (beige-300/-400, used only for
# gridlines and the dotted zero-line) do NOT use that formula: it barely
# moves a colour that starts near-white, which would leave gridlines
# invisible on a dark canvas — they map to --border's dark value instead,
# same as every other border in this app.
CHART_DARK: dict[str, str] = {
    # Tokens reused verbatim from _foundation.css.j2's dark block
    "#5A6F49": "#A9C48E",  # green-600 / --up
    "#A55A3C": "#D98E6B",  # terra-500 / --down
    "#8F8568": "#9A9078",  # beige-500 / --fg4
    "#3E392B": "#E4DDCC",  # beige-700 / --fg2
    "#1F1C15": "#F0EADB",  # beige-900 / --fg1
    "#F5F0E6": "#2A2619",  # beige-100, used as paper_bgcolor -> --bg-sunken dark
    "#FAF7F0": "#262218",  # beige-50, used as plot/legend bg -> --bg-raised dark
    # Near-white greys used only as gridlines/dotted guides: map to --border
    # dark, NOT the HSL formula (see module docstring above).
    "#DFD5BE": "#34301F",  # beige-300 gridlines/zeroline
    "#C4B89A": "#34301F",  # beige-400 quadrant/zero guide lines
    # Chart-only categorical colours, HSL-lightened (no semantic token)
    "#738A5F": "#A8B89B",  # green-500
    "#BF6F50": "#D5A795",  # terra-400
    "#455636": "#8BA474",  # green-700
    "#83462E": "#C5846A",  # terra-600
    "#6A8599": "#A4B3BF",  # info blue-gray (Data signal)
    "#2F3C25": "#7B9B63",  # green-800
    "#5E3121": "#BD6F54",  # terra-700
    "#8FA77A": "#BAC7AE",  # green-400
    "#8C8370": "#B7B2A7",  # muted annotation text inside chart JSON
    "#C8B89A": "#DCD3C2",  # sentiment-scatter marker outline / faded marker
    "#7A5B8E": "#AD98BA",  # THEME region colour (sentiment scatter)
}


def build_chart_dark_map() -> dict[str, str]:
    """Return the light->dark hex map every chart-rendering call site needs.

    A function rather than exposing CHART_DARK directly so callers (build.py,
    tests) have one stable name regardless of how the map itself is stored.
    """
    return dict(CHART_DARK)


# ---------------------------------------------------------------------------
# Base layout helper — eliminates ~80 lines of per-figure boilerplate
# ---------------------------------------------------------------------------

def _base_layout(**overrides) -> dict:
    """Return the common Plotly layout dict, merged with caller overrides.

    Nested dicts (xaxis, yaxis, title, font, legend, margin) are merged one
    level deep so callers can override individual keys without restating the
    whole sub-dict.
    """
    base = dict(
        paper_bgcolor="#F5F0E6",
        plot_bgcolor="#FAF7F0",
        font=dict(color="#3E392B", family="Inter, -apple-system, sans-serif"),
        legend=dict(bgcolor="#FAF7F0", bordercolor="#DFD5BE", font=dict(size=9)),
        margin=dict(l=50, r=20, t=50, b=50),
        hovermode="x unified",
    )
    # Shallow-merge nested dicts one level deep
    for key in ("xaxis", "yaxis", "yaxis2", "title", "font", "legend", "margin"):
        if key in overrides and key in base and isinstance(base[key], dict):
            merged = {**base[key], **overrides.pop(key)}
            base[key] = merged
        elif key in overrides:
            base[key] = overrides.pop(key)
    base.update(overrides)
    return base


def _fig_to_json(fig: go.Figure) -> str:
    """Serialize a figure, stripping Plotly's auto-applied default `template`.

    `pio.to_json` bakes in the FULL default-styling template — every trace
    type Plotly ships (choropleth, scatter3d, mesh3d, parcoords, and 20
    others this project never draws), not just the ones actually used
    (scatter/bar/heatmap). Found in the 2026-08-23 sweep: 26 serialized
    figures each carried their own copy, 63% of COHORT_CHARTS' bytes.

    Every visual property this project actually sets (colors, fonts,
    layout) is explicit in the figure already — nothing here reads from
    `layout.template`, confirmed by grep — so `template=None` is a pure
    strip: Plotly.js falls back to its own built-in default, which is
    exactly what the stripped blob was restating. Single chokepoint rather
    than the 11 independent `pio.to_json(fig)` call sites this replaced,
    so there is one place to keep this correct rather than 11 to remember.
    """
    fig.update_layout(template=None)
    return pio.to_json(fig)


# ---------------------------------------------------------------------------
# Figure builders
# ---------------------------------------------------------------------------

def _build_rrg_figure(rrg_df) -> str:
    """
    Relative Rotation Graph using real JdK-style RS-Ratio (x) and RS-Momentum (y).

    rrg_df: DataFrame with columns scan_id, run_at, region, gics_sector,
            rs_ratio, rs_momentum — from get_rrg_history().
    """
    if rrg_df is None or rrg_df.empty:
        fig = go.Figure()
        fig.update_layout(**_base_layout(
            title=dict(text="RRG — no data", font=dict(size=13, color="#3E392B")),
        ))
        return _fig_to_json(fig)

    import pandas as pd

    rrg_df = rrg_df.dropna(subset=["rs_ratio", "rs_momentum"]).copy()
    if rrg_df.empty:
        fig = go.Figure()
        fig.update_layout(**_base_layout(
            title=dict(text="RRG — no RS signals in DB yet",
                       font=dict(size=13, color="#3E392B")),
        ))
        return _fig_to_json(fig)

    latest_scan_id = rrg_df["scan_id"].max()
    latest = rrg_df[rrg_df["scan_id"] == latest_scan_id].copy()

    regions = sorted(rrg_df["region"].unique().tolist())
    color_palette = ["#5A6F49", "#A55A3C", "#738A5F", "#BF6F50", "#8FA77A"]
    region_colors = {r: color_palette[i % len(color_palette)] for i, r in enumerate(regions)}

    # Dynamic axis range: centre on 100, extend to fit all points + padding
    all_x = rrg_df["rs_ratio"].values
    all_y = rrg_df["rs_momentum"].values
    pad = 1.5
    x_min = min(all_x.min(), 100) - pad
    x_max = max(all_x.max(), 100) + pad
    y_min = min(all_y.min(), 100) - pad
    y_max = max(all_y.max(), 100) + pad

    fig = go.Figure()

    # Quadrant lines at 100/100
    fig.add_shape(type="line", x0=100, x1=100, y0=y_min, y1=y_max,
                  line=dict(color="#C4B89A", width=1, dash="dot"))
    fig.add_shape(type="line", x0=x_min, x1=x_max, y0=100, y1=100,
                  line=dict(color="#C4B89A", width=1, dash="dot"))

    # Quadrant labels
    qx_r = x_min + (x_max - x_min) * 0.82
    qx_l = x_min + (x_max - x_min) * 0.18
    qy_t = y_min + (y_max - y_min) * 0.88
    qy_b = y_min + (y_max - y_min) * 0.12
    for qx, qy, qlabel in [
        (qx_r, qy_t, "Leading"),
        (qx_l, qy_t, "Improving"),
        (qx_l, qy_b, "Lagging"),
        (qx_r, qy_b, "Weakening"),
    ]:
        fig.add_annotation(x=qx, y=qy, text=qlabel, showarrow=False,
                           font=dict(size=9, color="#8F8568"),
                           xanchor="center", yanchor="middle")

    # Tail traces — all scans except latest
    tail_df = rrg_df[rrg_df["scan_id"] != latest_scan_id]
    for region in regions:
        r_tail = tail_df[tail_df["region"] == region]
        for sector in r_tail["gics_sector"].unique():
            sec = r_tail[r_tail["gics_sector"] == sector].sort_values("scan_id")
            # Include the latest point to connect tail to current position before length check
            cur = latest[(latest["region"] == region) & (latest["gics_sector"] == sector)]
            if not cur.empty:
                sec = pd.concat([sec, cur]).sort_values("scan_id")
            if len(sec) < 2:
                continue
            fig.add_trace(go.Scatter(
                x=sec["rs_ratio"].tolist(),
                y=sec["rs_momentum"].tolist(),
                mode="lines+markers",
                line=dict(color=region_colors[region], width=1, dash="dot"),
                marker=dict(size=3, color=region_colors[region]),
                showlegend=False,
                hoverinfo="skip",
                opacity=0.35,
            ))

    # Main scatter — latest scan, one trace per region (for legend)
    for region in regions:
        r_latest = latest[latest["region"] == region]
        if r_latest.empty:
            continue
        fig.add_trace(go.Scatter(
            x=r_latest["rs_ratio"].tolist(),
            y=r_latest["rs_momentum"].tolist(),
            mode="markers+text",
            marker=dict(size=12, color=region_colors[region],
                        line=dict(width=1, color="#1F1C15")),
            text=r_latest["gics_sector"].tolist(),
            textposition="top center",
            textfont=dict(size=9),
            name=region,
            hovertemplate=(
                "<b>%{text} (" + region + ")</b><br>"
                "RS-Ratio: %{x:.2f}<br>"
                "RS-Momentum: %{y:.2f}<br>"
                "<extra></extra>"
            ),
        ))

    fig.update_layout(**_base_layout(
        title=dict(text="Relative Rotation Graph",
                   font=dict(size=13, color="#3E392B")),
        xaxis=dict(title="RS-Ratio (>100 = outperforming benchmark)",
                   range=[x_min, x_max], gridcolor="#DFD5BE", zeroline=False),
        yaxis=dict(title="RS-Momentum (>100 = RS-Ratio rising)",
                   range=[y_min, y_max], gridcolor="#DFD5BE", zeroline=False),
    ))
    return _fig_to_json(fig)


def _build_sentiment_scatter_figure(history_df) -> str:
    """Data <-> Sentiment scatter: x=data_score, y=sentiment_score, latest scan only."""
    if history_df.empty:
        fig = go.Figure()
        fig.update_layout(**_base_layout(
            title=dict(text="Data ⇄ Sentiment — no data",
                       font=dict(size=13, color="#3E392B")),
        ))
        return _fig_to_json(fig)

    latest_id = history_df["scan_id"].max()
    df = history_df[history_df["scan_id"] == latest_id].copy()

    has_sentiment = df["sentiment_score"].notna() & (df["sentiment_score"] != 0.0)
    solid = df[has_sentiment]
    faded = df[~has_sentiment]

    # The Sentiment page has never shown themes — its FinBERT signal table
    # stays cohort-scoped, and dashboard/sentiment.py reads the
    # history_df it passes into this builder down to sector regions before
    # calling it (see _sector_scoped_history), so a THEME row should never
    # actually reach here. The THEME entry below is defensive only: this is
    # a shared builder, not sentiment-page-specific, so it stays correct if
    # some other, unfiltered caller ever feeds it a THEME-inclusive frame.
    region_colors = {"US": "#A55A3C", "EU": "#5A6F49", "THEME": "#7A5B8E"}

    fig = go.Figure()

    for xy in [dict(x0=0, x1=0, y0=-3, y1=3), dict(x0=-3, x1=3, y0=0, y1=0)]:
        fig.add_shape(type="line", **xy, line=dict(color="#DFD5BE", width=1, dash="dot"))

    for x, y, label in [
        (1.5,  1.5, "Agreement<br>(bullish)"),
        (-1.5, 1.5, "Sentiment<br>ahead"),
        (-1.5, -1.5, "Agreement<br>(bearish)"),
        (1.5, -1.5, "Data ahead"),
    ]:
        fig.add_annotation(x=x, y=y, text=label, showarrow=False,
                           font=dict(size=9, color="#8C8370"),
                           xanchor="center", yanchor="middle")

    for region, color in region_colors.items():
        grp = solid[solid["region"] == region]
        if grp.empty:
            continue
        fig.add_trace(go.Scatter(
            x=grp["data_score"].tolist(),
            y=grp["sentiment_score"].tolist(),
            mode="markers+text",
            marker=dict(size=12, color=color, line=dict(width=1, color="#C8B89A")),
            text=grp["gics_sector"].tolist(),
            textposition="top center",
            textfont=dict(size=9, color="#3E392B"),
            name=region,
            hovertemplate=(
                "<b>%{text} (" + region + ")</b><br>"
                "Data: %{x:.3f}<br>Sentiment: %{y:.3f}<extra></extra>"
            ),
        ))

    if not faded.empty:
        fig.add_trace(go.Scatter(
            x=faded["data_score"].tolist(),
            y=[0.0] * len(faded),
            mode="markers+text",
            marker=dict(size=8, color="#C8B89A", symbol="circle-open"),
            text=faded["gics_sector"].tolist(),
            textposition="top center",
            textfont=dict(size=8, color="#8C8370"),
            name="no sentiment data",
            hovertemplate="<b>%{text}</b><br>Sentiment: N/A<extra></extra>",
        ))

    fig.update_layout(**_base_layout(
        title=dict(text="Data ⇄ Sentiment", font=dict(size=13, color="#3E392B")),
        xaxis=dict(title="Data Score", gridcolor="#DFD5BE", zeroline=False),
        yaxis=dict(title="Sentiment Score", gridcolor="#DFD5BE", zeroline=False),
        height=520,
    ))
    return _fig_to_json(fig)


def _build_drilldown_data(history_df) -> tuple[dict, list[str]]:
    """
    Build per-sector timeseries for each score column.
    Returns (sector_signal_data, sector_keys, score_signals).

    sector_signal_data: { sector_key: plotly_figure_json }
    """
    import pandas as pd

    score_signals = _DRILLDOWN_SIGNALS

    if history_df.empty:
        return {}, [], score_signals

    sector_keys = (history_df["region"] + "|" + history_df["gics_sector"]).unique().tolist()
    sector_keys.sort()

    history_df = history_df.copy()
    history_df["sector_key"] = history_df["region"] + "|" + history_df["gics_sector"]
    history_df["run_at_str"] = pd.to_datetime(history_df["run_at"], format="ISO8601", utc=True).dt.strftime("%Y-%m-%d")

    # Per-sector per-signal breakdown (used by the drilldown tab)
    sector_signal_data: dict[str, str] = {}
    for sk in sector_keys:
        sk_data = history_df[history_df["sector_key"] == sk].sort_values("scan_id")
        if sk_data.empty:
            continue
        region, sector_name = sk.split("|", 1)
        fig = go.Figure()
        for signal in score_signals:
            if signal not in sk_data.columns:
                continue
            fig.add_trace(go.Scatter(
                x=sk_data["run_at_str"].tolist(),
                y=sk_data[signal].tolist(),
                mode="lines+markers",
                name=signal.replace("_", " ").title(),
                line=dict(color=_SCORE_SIGNAL_COLORS.get(signal, "#8F8568")),
                hovertemplate=f"<b>{signal}</b><br>Date: %{{x}}<br>Value: %{{y:.3f}}<extra></extra>",
            ))
        fig.update_layout(**_base_layout(
            title=dict(text=f"{sector_name} ({region}) — score components",
                       font=dict(size=13, color="#3E392B")),
            xaxis=dict(title="Scan Date", gridcolor="#DFD5BE"),
            yaxis=dict(title="Score / Rank", gridcolor="#DFD5BE"),
        ))
        sector_signal_data[sk] = _fig_to_json(fig)

    return sector_signal_data, sector_keys, score_signals


def _build_movers_figure(history_df) -> str:
    """Bar chart of delta_rank for the most recent scan, sorted."""
    import pandas as pd

    if history_df.empty or len(history_df["scan_id"].unique()) < 2:
        fig = go.Figure()
        fig.update_layout(**_base_layout(
            title=dict(text="Movers — need at least 2 scans",
                       font=dict(size=13, color="#3E392B")),
        ))
        return _fig_to_json(fig)

    scan_ids = sorted(history_df["scan_id"].unique())
    latest_id = scan_ids[-1]
    prev_id = scan_ids[-2]

    latest = history_df[history_df["scan_id"] == latest_id][
        ["region", "gics_sector", "rank", "composite"]
    ].rename(columns={"rank": "rank_cur", "composite": "comp_cur"})

    prev = history_df[history_df["scan_id"] == prev_id][
        ["region", "gics_sector", "rank", "composite"]
    ].rename(columns={"rank": "rank_prev", "composite": "comp_prev"})

    merged = latest.merge(prev, on=["region", "gics_sector"], how="inner")
    merged["delta_rank"] = merged["rank_prev"] - merged["rank_cur"]
    merged["label"] = merged["gics_sector"] + " (" + merged["region"] + ")"
    merged = merged.sort_values("delta_rank", ascending=True)

    colors = ["#8FA77A" if d >= 0 else "#BF6F50" for d in merged["delta_rank"]]

    fig = go.Figure(go.Bar(
        x=merged["delta_rank"].tolist(),
        y=merged["label"].tolist(),
        orientation="h",
        marker_color=colors,
        hovertemplate=(
            "<b>%{y}</b><br>"
            "Rank change: %{x:+.1f}<br>"
            "<extra></extra>"
        ),
    ))

    fig.update_layout(**_base_layout(
        title=dict(text="Movers — rank change (latest vs prior scan)",
                   font=dict(size=13, color="#3E392B")),
        xaxis=dict(title="Delta rank (positive = climbing)", gridcolor="#DFD5BE",
                   zeroline=True, zerolinecolor="#C4B89A"),
        yaxis=dict(title="", gridcolor="#DFD5BE"),
        margin=dict(l=180, r=30, t=50, b=50),
        height=max(300, len(merged) * 28 + 80),
    ))
    return _fig_to_json(fig)


def _build_history_figure(history_df) -> str:
    """Line chart of composite rank over time, one line per sector+region."""
    import pandas as pd

    if history_df.empty:
        fig = go.Figure()
        fig.update_layout(**_base_layout(
            title=dict(text="History — no data",
                       font=dict(size=13, color="#3E392B")),
        ))
        return _fig_to_json(fig)

    df = history_df.copy()
    df["sector_label"] = df["gics_sector"] + " (" + df["region"] + ")"
    df["run_at_str"] = pd.to_datetime(df["run_at"], format="ISO8601", utc=True).dt.strftime("%Y-%m-%d")
    df = df.sort_values("scan_id")

    fig = go.Figure()
    for i, label in enumerate(sorted(df["sector_label"].unique())):
        sec = df[df["sector_label"] == label]
        fig.add_trace(go.Scatter(
            x=sec["run_at_str"].tolist(),
            y=sec["composite"].tolist(),
            mode="lines+markers",
            name=label,
            line=dict(color=_WARM_PALETTE[i % len(_WARM_PALETTE)]),
            hovertemplate=f"<b>{label}</b><br>Date: %{{x}}<br>Composite: %{{y:.3f}}<extra></extra>",
        ))

    fig.update_layout(**_base_layout(
        title=dict(text="Composite score history", font=dict(size=13, color="#3E392B")),
        xaxis=dict(title="Scan Date", gridcolor="#DFD5BE"),
        yaxis=dict(title="Composite score", gridcolor="#DFD5BE"),
    ))
    return _fig_to_json(fig)


def _track_label(track: dict, key: str) -> str:
    """Human name for a track, with its policy spelled out — the chart title is
    where a reader learns what "Long" actually means.

    Shown as a percentage of the universe (buffer_frac), not an absolute rank
    count — same reasoning and convention as `buffer_pct` below: a multi-year
    backtest run's universe size varies throughout, so there's no single
    honest "today's universe" to convert against."""
    freq = track.get("rebalance_freq", "M")
    buffer_pct = f"{100 * track.get('buffer_frac', 0.0):.0f}%"
    return (f"{key.title()} — top {track.get('top_n')}, "
            f"buffer {buffer_pct}, {freq} rebalance")


def _build_backtest_figures(summary) -> dict:
    """Per-track equity curves (strategy vs benchmark). Returns {region: fig_json}."""
    if not summary or not summary.get("tracks"):
        return {}
    figs: dict[str, str] = {}
    for region, track in summary["tracks"].items():
        if not track or not track.get("equity_curve"):
            continue
        dates = [p["date"] for p in track["equity_curve"]]
        strat = [p["strategy"] for p in track["equity_curve"]]
        bench = [p["benchmark"] for p in track["equity_curve"]]
        fig = go.Figure()
        fig.add_trace(go.Scatter(x=dates, y=strat, mode="lines",
                                 name=f"Top {track['top_n']} strategy",
                                 line=dict(color=_WARM_PALETTE[0])))
        fig.add_trace(go.Scatter(x=dates, y=bench, mode="lines",
                                 name=f"Benchmark ({track['benchmark']})",
                                 line=dict(color=_WARM_PALETTE[3], dash="dash")))
        fig.update_layout(**_base_layout(
            title=dict(text=f"{_track_label(track, region)} — growth of 1.0",
                       font=dict(size=13, color="#3E392B")),
            xaxis=dict(title="Date", gridcolor="#DFD5BE"),
            yaxis=dict(title="Equity (×)", gridcolor="#DFD5BE"),
        ))
        figs[region] = _fig_to_json(fig)
    return figs


def _build_backtest_context(backtests_dir: str) -> dict:
    """Load summary.json and shape it for the template."""
    import json as _json
    from src.backtest.results import load_summary

    from src.horizons import horizons
    labels = {h.key: h.label for h in horizons()}

    summary = load_summary(backtests_dir)
    figs = _build_backtest_figures(summary)
    rows: list[dict] = []
    if summary:
        for region, track in summary["tracks"].items():
            if not track:
                continue
            m = track["metrics"]
            rows.append({
                "region": region, "start": track["start"], "end": track["end"],
                "benchmark": track["benchmark"], "top_n": track["top_n"],
                "label": labels.get(region, region.title()),
                "rebalance": track.get("rebalance_freq", "M"),
                # Displayed as a percentage of the universe, not an absolute rank
                # count: a multi-year backtest run's universe size varies
                # throughout, so there is no single honest "convert to an
                # absolute count" reference point (unlike the live dashboard,
                # which has "today's universe"). Matches the idea behind
                # scripts/horizon_sweep.py's own `band` column — show a share
                # of the universe rather than a raw rank — though that column
                # is (top_n + buffer) / universe (the whole band width), while
                # this is buffer_frac alone (buffer only, excluding top_n).
                "buffer_pct": f"{100 * track.get('buffer_frac', 0.0):.0f}%",
                "cagr": f"{100 * m['cagr']:.1f}%",
                "benchmark_cagr": f"{100 * m['benchmark_cagr']:.1f}%",
                "sharpe": f"{m['sharpe']:.2f}",
                "max_drawdown": f"{100 * m['max_drawdown']:.1f}%",
                "hit_rate": f"{100 * m['hit_rate']:.0f}%",
                "avg_turnover": f"{100 * m['avg_turnover']:.0f}%",
                # The churn cost, shown beside the return so a preset can never
                # be chosen on CAGR alone.
                "trades_per_year": (f"{m['trades_per_year']:.0f}"
                                    if m.get("trades_per_year") else "—"),
                "median_holding_days": (f"{m['median_holding_days']:.0f}"
                                        if m.get("median_holding_days") else "—"),
            })
    return {
        "backtest_json": _json.dumps({k: _json.loads(v) for k, v in figs.items()}),
        "backtest_metrics": rows,
        "has_backtest": bool(figs),
    }


# Trailing windows for the summary strip's performance chips, in days.
# Two windows, not one: the window picks the story. Measured 2026-09-05,
# `medium` read +1.2pp over 1M and +32.2pp over 12M -- showing either alone
# invites the reader to over-update on an arbitrary framing. See
# sector_momentum-notes/specs/2026-09-05-strategy-track-record-chip-design.md.
_TRACK_WINDOW_DAYS = {"m1": 30, "m12": 365}

# backtests/summary.json refreshes only on a manual `python3 backtest.py`.
# Past this, a window labelled "1M" is measuring a month that ended long ago.
_TRACK_STALE_AFTER_DAYS = 35


def _window_excess(equity_curve: list[dict], days: int) -> tuple[float, str] | None:
    """Excess return (strategy - benchmark) in percentage points over the
    trailing `days`, with the actual from-date it was measured from.

    Anchored by DATE, never by list index: engine.py appends one calendar
    date past the final rebalance, so the curve's last point is a stub a day
    after the last real rebalance. Indexing back one point would measure a
    single day and render labelled as a month.

    Returns None when the curve does not reach back far enough -- a short
    track shows no figure rather than one measured from its own first point.
    """
    from datetime import date as _date, timedelta as _timedelta

    if not equity_curve:
        return None
    last = equity_curve[-1]
    try:
        end = _date.fromisoformat(last["date"])
    except (KeyError, ValueError):
        return None

    target = end - _timedelta(days=days)
    prior = [p for p in equity_curve
             if _date.fromisoformat(p["date"]) <= target]
    if not prior:
        return None
    start = prior[-1]

    # 0 or None on either leg would make the ratio meaningless or raise.
    if not start.get("strategy") or not start.get("benchmark"):
        return None
    if last.get("strategy") is None or last.get("benchmark") is None:
        return None

    strat = last["strategy"] / start["strategy"]
    bench = last["benchmark"] / start["benchmark"]
    return (100.0 * (strat - bench), start["date"])


def _live_horizon_stats(backtests_dir: str, today: date | None = None) -> dict[str, dict]:
    """{horizon_key: {"trades_per_year": float | None, "median_holding_days":
    float | None, "m1"/"m12": float | None (excess pp vs benchmark over the
    trailing 30/365 days), "m1_from"/"m12_from": str | None (the actual
    curve date each was measured from), "as_of": str | None, "stale": bool}}
    from backtests/summary.json's live measured metrics.

    `today` is injectable so the staleness flag is testable, matching
    dashboard/gating.py::_pick_lagged_scan's `now` parameter.

    A second, independent read of the same artifact _build_backtest_context
    loads above: that function pre-formats these same numbers into display
    strings for the Backtest tab's server-rendered table (e.g. "21" or
    "—"), while the horizon-selector chip's client-side JS
    (renderHorizonStats() in index.html.j2) needs raw numbers to do its own
    Math.round(). Two different shaping needs, one small cheap file read
    each -- not worth entangling into one shared function with two output
    modes.

    A horizon key absent from the returned dict means "no data" (file
    missing, or that horizon has no track) -- callers treat a missing key
    the same as an explicit None value, matching the chip's existing
    em-dash fallback for a null trades_per_year/median_holding_days.
    """
    from src.backtest.results import load_summary

    ref_today = today or date.today()
    summary = load_summary(backtests_dir)
    stats: dict[str, dict] = {}
    for key, track in (summary or {}).get("tracks", {}).items():
        if not track:
            continue
        m = track.get("metrics") or {}
        curve = track.get("equity_curve") or []
        entry = {
            "trades_per_year": m.get("trades_per_year"),
            "median_holding_days": m.get("median_holding_days"),
            "as_of": track.get("end"),
            "stale": False,
        }
        for name, days in _TRACK_WINDOW_DAYS.items():
            got = _window_excess(curve, days)
            entry[name] = got[0] if got else None
            entry[f"{name}_from"] = got[1] if got else None

        end_str = track.get("end")
        if end_str:
            try:
                age = (ref_today - date.fromisoformat(end_str)).days
                entry["stale"] = age > _TRACK_STALE_AFTER_DAYS
            except ValueError:
                entry["stale"] = False
        stats[key] = entry
    return stats


def _build_rescore_data(history_df) -> dict:
    """Per-scan x per-sector data_score and sentiment_score arrays for the
    client-side leaderboard rescoring."""
    if history_df.empty:
        return {"scans": [], "sectors": [], "data": {}, "sentiment": {}}

    df = history_df.copy()
    df["sector_key"] = df["region"] + "|" + df["gics_sector"]

    scan_ids = sorted(df["scan_id"].unique().tolist())
    scans_meta = []
    for sid in scan_ids:
        run_at = df[df["scan_id"] == sid]["run_at"].iloc[0]
        scans_meta.append({"scan_id": int(sid), "run_at": str(run_at)})

    sectors = sorted(df["sector_key"].unique().tolist())

    def _series(col: str) -> dict:
        result = {}
        for key in sectors:
            sk = df[df["sector_key"] == key].groupby("scan_id")[col].first()
            vals = []
            for sid in scan_ids:
                fv = _safe_float(sk.get(sid))
                vals.append(fv if fv is not None else 0.0)
            result[key] = vals
        return result

    return {
        "scans": scans_meta,
        "sectors": sectors,
        "data": _series("data_score"),
        "sentiment": _series("sentiment_score"),
    }


def _build_scan_history_data(all_scores_df) -> dict:
    """Per-scan scores for every sector, for the client-side scan-history viewer."""
    if all_scores_df.empty:
        return {"scans": [], "scores": {}}

    df = all_scores_df.copy()

    scan_ids = sorted(df["scan_id"].unique(), reverse=True)
    scans = []
    for sid in scan_ids:
        g = df[df["scan_id"] == sid]
        run_at_raw = str(g["run_at"].iloc[0])
        try:
            disp = pd.to_datetime(run_at_raw).strftime("%Y-%m-%d %H:%M UTC")
        except (ValueError, TypeError):
            disp = run_at_raw
        top = g.loc[g["rank"].idxmin()]
        scans.append({
            "id": int(sid),
            "date": disp,
            "sectors": int(len(g)),
            "top": f"{top['gics_sector']} ({top['region']})",
        })

    scores = {}
    for sid in scan_ids:
        g = df[df["scan_id"] == sid]
        sid_scores = {}
        for _, row in g.iterrows():
            key = f"{row['region']}|{row['gics_sector']}"
            rk = _safe_float(row["rank"])
            sid_scores[key] = {
                "rank": int(rk) if rk is not None else 99,
                "composite": round(_safe_float(row["composite"]) or 0.0, 3),
                "level": round(_safe_float(row["level_score"]) or 0.0, 3),
                "change": round(_safe_float(row["change_score"]) or 0.0, 3),
                "data": round(_safe_float(row["data_score"]) or 0.0, 3),
                "sentiment": round(_safe_float(row["sentiment_score"]) or 0.0, 3),
            }
        scores[str(int(sid))] = sid_scores

    return {"scans": scans, "scores": scores}


# ---------------------------------------------------------------------------
# Page context builders
# ---------------------------------------------------------------------------

def build_sectors_context(shared: dict) -> dict:
    """Assemble the non-chart figure + backtest context entries for the
    sectors page.

    The four per-cohort chart entries (RRG, Movers, History, Drill-down) live
    in `build_cohort_chart_context` instead — one cohort at a time, sliced by
    region, rather than one shared cross-cohort figure. See that function's
    docstring for why (mixed-cohort RRG/History figures would plot different
    benchmarks — RSP, EXSA.DE, ACWI — on the same axis).
    """
    import json as _json

    signals_list = _DRILLDOWN_SIGNALS
    rescore_data_json = _json.dumps(_build_rescore_data(shared["history_df"]))
    scan_history_json = _json.dumps(_build_scan_history_data(shared["all_scores_df"]))
    bt = _build_backtest_context(str(shared["project_root"] / "backtests"))

    return {
        "signals_list": signals_list,
        "rescore_data_json": rescore_data_json,
        "scan_history_json": scan_history_json,
        "backtest_json": bt["backtest_json"],
        "backtest_metrics": bt["backtest_metrics"],
        "has_backtest": bt["has_backtest"],
    }


def build_cohort_chart_context(shared: dict) -> dict:
    """One chart context per configured cohort (US, EU, THEME).

    rs_ratio/rs_momentum are computed against each cohort's own benchmark
    (themes vs ACWI, US sectors vs RSP, EU vs EXSA.DE — src/pipeline.py), so
    plotting cohorts together on one RRG/History figure would put "5% above
    ACWI" and "5% above RSP" on the same axis. This builder slices
    `shared["history_df"]` and `shared["rrg_df"]` to each cohort's region and
    calls the existing (unmodified) figure builders per slice, rather than
    building one mixed-cohort figure.

    Returns {"cohort_charts": {region: {...}}, "cohort_charts_json": "..."}
    — the dict form for Python callers/tests, the serialised form for direct
    embedding as the template's `COHORT_CHARTS` JS blob (mirrors the
    load-then-redump pattern `_build_backtest_context` already uses for
    `backtest_json`, so NaN/Infinity survive the round-trip the same way).
    """
    import json as _json

    from src.cohorts import cohorts

    themes_cfg = shared.get("themes_cfg")
    history_df = shared["history_df"]
    rrg_df = shared["rrg_df"]

    cohort_charts: dict[str, dict] = {}
    for cohort in cohorts(themes_cfg):
        region = cohort.region
        region_history = history_df[history_df["region"] == region]
        region_rrg = rrg_df[rrg_df["region"] == region]

        rrg_json = _build_rrg_figure(region_rrg)
        movers_json = _build_movers_figure(region_history)
        history_json = _build_history_figure(region_history)
        drilldown_raw, sector_keys, _ = _build_drilldown_data(region_history)

        cohort_charts[region] = {
            "rrg": _json.loads(rrg_json),
            "movers": _json.loads(movers_json),
            "history": _json.loads(history_json),
            "drilldown": {k: _json.loads(v) for k, v in drilldown_raw.items()},
            "keys": sector_keys,
        }

    return {
        "cohort_charts": cohort_charts,
        "cohort_charts_json": _json.dumps(cohort_charts),
    }
