"""
Report generator.

Produces a Markdown report from scored/ranked sector data.
Outputs to reports/report_<YYYY-MM-DD>.md
"""

from __future__ import annotations

import os
from pathlib import Path

import pandas as pd

from src.cohorts import Cohort


def build_ranked_table(scores_with_deltas: pd.DataFrame, cohort_list: list[Cohort]) -> str:
    """
    Build a markdown table of all sectors ranked by composite score,
    split into per-cohort sections (in `cohort_list` order) with per-cohort ranks.
    """
    header = "| Rank | Sector | Composite | Level | Change | ΔRank | ΔComposite | ⭐ |"
    separator = "|------|--------|-----------|-------|--------|-------|------------|---|"

    sections = []
    for cohort in cohort_list:
        region_df = scores_with_deltas[scores_with_deltas["region"] == cohort.region]
        if region_df.empty:
            continue
        region_df = region_df.sort_values("rank", ascending=True).reset_index(drop=True)

        rows = [f"## {cohort.label}", "", header, separator]
        for _, row in region_df.iterrows():
            rank = int(row["rank"])
            sector = row["gics_sector"]
            composite = f"{row['composite']:.2f}"
            level = f"{row['level_score']:.2f}"
            change = f"{row['change_score']:.2f}"
            delta_rank = int(row.get("delta_rank", 0))
            delta_rank_str = f"{delta_rank:+d}"
            delta_composite_val = row.get("delta_composite", 0.0)
            delta_composite = f"{delta_composite_val:.2f}"
            star = "🌱" if row.get("emerging_flag", False) else ""
            rows.append(
                f"| {rank} | {sector} | {composite} | {level} | {change} | {delta_rank_str} | {delta_composite} | {star} |"
            )
        sections.append("\n".join(rows))

    return "\n\n".join(sections)


def build_movers(scores_with_deltas: pd.DataFrame, top_n: int = 5) -> str:
    """
    Build a markdown section highlighting the biggest movers.

    Returns a markdown string with two sub-sections:
    ## 🚀 Top Climbers (by ΔRank)
    - List of top_n sectors with largest positive delta_rank

    ## ⚠️ Biggest Fallers (by ΔRank)
    - List of top_n sectors with largest negative delta_rank

    Each entry format: "**{sector}** ({region}): rank {rank} (Δ{delta_rank:+d})"
    """
    df = scores_with_deltas.copy()

    # Guard against missing delta_rank column (first scan)
    if 'delta_rank' not in df.columns:
        return "_No delta data available (first scan)._\n"

    # Top climbers: largest positive delta_rank (ascending rank = better)
    # A positive delta_rank means the rank number went up (fell in standings),
    # but in the context of "climbers" we want sectors whose rank improved (rank number decreased).
    # The spec says "largest positive delta_rank" so we follow the spec literally.
    climbers = df.sort_values("delta_rank", ascending=False).head(top_n)
    fallers = df.sort_values("delta_rank", ascending=True).head(top_n)

    def format_entry(row: pd.Series) -> str:
        sector = row["gics_sector"]
        region = row["region"]
        rank = int(row["rank"])
        delta_rank = int(row.get("delta_rank", 0))
        return f"- **{sector}** ({region}): rank {rank} (Δ{delta_rank:+d})"

    climber_lines = [format_entry(row) for _, row in climbers.iterrows()]
    faller_lines = [format_entry(row) for _, row in fallers.iterrows()]

    parts = [
        "## 🚀 Top Climbers (by ΔRank)",
        "\n".join(climber_lines) if climber_lines else "- None",
        "",
        "## ⚠️ Biggest Fallers (by ΔRank)",
        "\n".join(faller_lines) if faller_lines else "- None",
    ]

    return "\n".join(parts)


def build_report_markdown(
    scan_date: str,
    ranked_table: str,
    movers: str,
) -> str:
    """Compose the full report Markdown string (no file I/O)."""
    return f"""# Sector Momentum Report — {scan_date}
> Analytical tooling, not investment advice.

## Rankings
{ranked_table}

## Movers
{movers}

---
*Generated by Sector Momentum Scanner. Last scan: {scan_date}.*
"""


def write_report(
    scan_date: str,        # "YYYY-MM-DD"
    ranked_table: str,
    movers: str,
    output_dir: str = "reports",
) -> str:
    """
    Compose and write the full report to reports/report_<scan_date>.md.

    Report structure:
    # Sector Momentum Report — {scan_date}
    > Analytical tooling, not investment advice.

    ## Rankings
    {ranked_table}

    ## Movers
    {movers}

    ---
    *Generated by Sector Momentum Scanner. Last scan: {scan_date}.*

    Returns the path of the written file.
    """
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    filepath = os.path.join(output_dir, f"report_{scan_date}.md")
    with open(filepath, "w", encoding="utf-8") as fh:
        fh.write(build_report_markdown(scan_date, ranked_table, movers))
    return filepath
